### PR TITLE
Add superior figures for italic, bold and bold italic

### PR DESCRIPTION
**Pull request by dbenjaminmiller**
I added the glyphs for superior figures (from URW's source), as well as the OpenType for them. I also included the minute and second symbols from URW in the bold italic.

### CODE REVIEW

**Comment by khaledhosny** [comment]
No need to copy the glyphs from another font, they can be taken from the glyphs for  ¹, ¾, ⅚, and the likes. Might not give you all the glyphs, but the few missing can be copied from another font or drawn from the full-size glyphs to match the style of the small ones.

**Comment by dbenjaminmiller** [comment]
I should clarify. The ones I was able to find in XITS I copied in. I used URW to fill the gaps. You can look at the URW glyphs present in my commit—they fit well, to my eye.

**Comment by khaledhosny** [comment]
Which ones were copied from URW fonts?

**Comment by dbenjaminmiller** [comment]
0, 4, 5, 6, 7, 8, 9 are URW. 1, 2, 3 are XITS/STIX—the same superior figures already present. The only other number in the sources in question's fractions is 4, but you'll notice that the precomposed fractions are a different size from the superior figures, and that the 3 in ¾, for example, isn't the same as the provided superscript 3 in size. So I prefer the ones which are actually the optical size—hence the use of the URW 4. The others glyphs are not present in fractional or superior form, so they are taken from URW and fit quite well.

There is only one glyph which is problematic—that being the 1, in the italic and bold italic fonts (though not the bold). It seems weirdly spaced to me. However, this was a XITS/STIX character, and I made no changes to it. The 2 and 3 don't suffer from this issue; it's more of a STIX-originating bug than anything. So I didn't change it in this PR.

**Comment by khaledhosny** [comment]
OK. I the regular font the glyphs are tabular (All have the same width), but yours are proportional. I think all should be tabular for consistency and to match the full-size digits.

**Comment by dbenjaminmiller** [comment]
OK, I will go try to make that change now...

**Comment by dbenjaminmiller** [comment]
Strange. They all seem tabular to me (width of 300).

**Comment by khaledhosny** [comment]
Right, I was confused. Regular ones are 350 units, though, and they should be the same width as full-sized digits has the same width across the all the fonts.

**Comment by dbenjaminmiller** [comment]
They're the same width as the superior figures for 1, 2 and 3 already
present in XITS' non-regular faces. I'm not sure of the origin of the
design choice.

**Comment by khaledhosny** [comment]
We can ignore the old glyphs for now (they should be fixed, but I’d rather not change the metrics of existing glyphs at this point).

**Comment by dbenjaminmiller** [comment]
So then, what do you think one should do here? Honestly, I don't mind how
things currently look — and given that they're only enabled as OTF
superscripts, and not as numerators properly, this shouldn't result in any
messy fractions. I suppose one could decide later if the superiors should
be 350 or 300. Perhaps split the sups into their own glyphs — leave
one.numr, etc the same while making one.sups, etc. Leave the numerators
alone and change the sups' metrics in regular to 300. (or, vice versa and
don't change anything)

**Comment by khaledhosny** [comment]
Make the new glyphs (the `*.numr` glyphs) all have a width of 350, and leave the existing glyphs as there are.

**Comment by dbenjaminmiller** [comment]
I wonder how a simple 25+25 would look for these purposes. (As if metrics
were ever simple)

**Comment by dbenjaminmiller** [comment]
Take a look at the onesuperior, twosuperior, threesuperior in the original fonts. They are the same outlines as the numr figures, but with a width of 300. So I coped the outline to one.sups, two.sups, etc.; they will need to be reduced from 350 to 300 to match the superiors. I'll do that in a little bit

**Comment by dbenjaminmiller** [comment]
I am going to submit a second PR with a better approach…

**Pull request closed without merging**
