### PR TITLE
Add superior figures and ffj ligature

### PR DESCRIPTION
**Pull request by dbenjaminmiller**
This change includes the following:

* Added superior figures from URW upstream sources (the requisite copyright notices had already been included). Unlike in my previously-merged change, these are not the fractional figures.

⇒ _Why use URW's superior figures and not the fractional figures?_ The use case is different; in this case, the purpose is for footnotes, and thus the characters, while still lining characters, are narrower than the fractional figures (300 vs. 350). The fractional figures cannot work at this width — slightly narrower characters were needed even where the fractional figures were present. Trying to use the fractional figures resulted in either ugliness arising from trying to use glyphs which were too wide for 300-width, or ugliness resulting from using 350-width superior figures (esp. when mixing the fractional 0, 1, … 3 with the URW 4, 5, … 9). The gylphs used in the precomposed fractions, while perhaps to the naked eye substantially similar to what is needed, were in fact of a different size and were thus also unsuitable for these purposes. Hence, I have separated the superior figures from the fractions. The fractional figures remain the stock STIX/XITS ones; only the added superior figures in each face are using URW glyphs. The URW glyphs were preferable to others because they were OFL-licensed, professionally-drawn, created for this specific (superior figures) purpose, decent-looking and created specifically for a font family which matches this one virtually exactly.

* Added an ffj ligature — very rare in English ("cliffjumper") but does find use in some other languages. There was already fj so it wasn't so hard to put together.

### CODE REVIEW

**Comment by dbenjaminmiller** [comment]
(It didn't make sense to make this two commits due to the combined nature of the changes in the compiled font files.)

**Comment by dbenjaminmiller** [comment]
(Also, between this and the previous bugfix, I think that a release could be done.)

**Comment by khaledhosny** [comment]
Thanks! (I took the liberty to do some minor changes to the SFD files before merging).

**Comment by dbenjaminmiller** [comment]
Great. Out of curiosity, what was the change?

**Comment by khaledhosny** [comment]
You can see them from the forced-push link above. Mostly removing superfluous stuff FontForge keeps in SFD files that makes version control a  bit harder, and some unintended changes.

**Pull request merged**
